[linters]
disable-all = false
enable = [
  "staticcheck",
  "unused",
  "govet",
  "gocyclo",
  "gosec",
  "makezero",
  "prealloc",
  "usestdlibvars",
  "whitespace",
  #  "errcheck",
]

disable = ["errcheck","ineffassign"]

[linters-settings.govet]
check-shadowing = true
check-unreachable = true
check-rangeloops = true
check-copylocks = true
enable = ["nilness"]
