# linters:
#   disable-all: false
#   enable:
#     - staticcheck
#     - structcheck
#     - govet
#     - deadcode
#     - gocyclo
#     - gosec
#     - makezero
#     - prealloc
#     - usestdlibvars
#     - revive
#     - whitespace
#     - wsl
#     - errcheck
#   # diable:
#   #   - errcheck
# linters-settings:
#   govet:
#    check-shadowing: true
#    check-unreachable: true
#    check-rangeloops: true
#    check-copylocks: true
#    enable:
#      - nilness

[linters]
disable-all = false
enable = [
  "staticcheck",
  "unused",
  "govet",
  "gocyclo",
  "gosec",
  "makezero",
  "prealloc",
  "usestdlibvars",
  "revive",
  "whitespace",
  # "errcheck",
]
disable = ["errcheck"]

[linters-settings.govet]
check-shadowing = true
check-unreachable = true
check-rangeloops = true
check-copylocks = true
enable = ["nilness"]
